Repository carbon-design-system/carbon-components-react, pull requests merged in 2018-11, with the labels that each got.

#1522 fix: add DatePickerSkeleton to default export
  src/index.js
Labels: status: ready for review :eyes:

#1370 fix(Slider): prop -> state sync for values
  .storybook/webpack.config.js
  src/components/Slider/Slider-story.js
  src/components/Slider/Slider.js
  src/internal/FeatureFlags.js
Labels: type: discussion 💬, v10 :new:

#1534 fix(number-input): add helpertext class when helper text is present
  src/components/NumberInput/NumberInput.js
Labels: status: one more review :eyes:

#1546 chore: reorder storybook addons to show story first
  .storybook/addons.js
Labels: status: ready for review :eyes:

#1523 feat(Tag): add experimental tag component
  src/components/Tag/Tag-story.js
  src/components/Tag/Tag.js
Labels: status: ready for review :eyes:, status: visual review :eyes:

#1528 feat(StructuredList): add experimental structured list
  src/components/StructuredList/StructuredList-story.js
Labels: status: visual review :eyes:

#1537 feat(Notification): add experimental notification
  src/components/Notification/Notification-story.js
  src/components/Notification/Notification-test.js
  src/components/Notification/Notification.js
  src/components/Notification/a11yIconWarningSolid.js
Labels: status: ready for review :eyes:, status: visual review :eyes:, type: dev :robot:

#1502 fix(#1100): when there is a selected value, show cancel button and all the elements on expand
  src/components/ComboBox/ComboBox-test.js
  src/components/ComboBox/ComboBox.js
  src/components/MultiSelect/FilterableMultiSelect.js
Labels: status: one more review :eyes:

#1578 feat(InlineCheckbox): allow optional tooltip
  src/components/InlineCheckbox/InlineCheckbox.js
Labels: status: one more review :eyes:, status: ready for review :eyes:

#1572 Fix number input controls misalignment
  src/components/NumberInput/NumberInput-test.js
  src/components/NumberInput/NumberInput.js
Labels: status: one more review :eyes:

#1577 fix(Search): provide a default value
  src/components/Search/Search-story.js
Labels: status: one more review :eyes:

#1576 fix(FileUploaderButton): handle container div onClick
  package.json
  src/components/FileUploader/FileUploader-test.js
  src/components/FileUploader/FileUploader.js
Labels: status: ready for review :eyes:

#1573 feat(FileUploaderButton): add disabled prop
  src/components/FileUploader/FileUploader-story.js
  src/components/FileUploader/FileUploader-test.js
  src/components/FileUploader/FileUploader.js
Labels: status: failing tests :no_good_man:, status: one more review :eyes:
